### PR TITLE
Readonly Test Coverage of Medbook-CRFs

### PR DESCRIPTION
**Pull request by awatson1978**
- 919 acceptance tests; all green
- tests for each column in each table
- tests for each input in each form
- no form inputs yet

### CODE REVIEW

**Comment by awatson1978** [comment]
Need to sync up before I write the interactive tests; but this is a huge chunk of coverage, a good milestone, and worth merging in at this point.

**Comment by awatson1978** [comment]
Need to sync up before I write the interactive tests; but this is a huge chunk of coverage, a good milestone, and worth merging in at this point.

@rbaertsch - want to pull the branch and test?  Or just merge directly in?

**Comment by rbaertsch** [comment]
monday is good

**Comment by awatson1978** [comment]
Was the intent that we fill out the forms with the sample data from patients DTB-003, DTB-004, and DTB-005?  Or that we merely ingest the sample data, and confirm that it displays in the tables correctly?  

Put another way:  does the sample data in DTB-003 contain a complete sample patient?  Is it everything I need to fill out the forms?  Or should I simply pick the first value in each select drop-down and use random strings to fill out the forms if it's not otherwise specified?

**Pull request merged**
